var DATA = [
  {
    created_at: "Wed Jan 13 09:23:07 +0000 2021",
    id: 1349285840682426400,
    id_str: "1349285840682426368",
    text:
      "BREAKING: Russian opposition politician Alexey Navalny says he will return to Russia from Germany, where he has bee… https://t.co/uq0oN9JY9s",
    truncated: true,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
    source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 759251,
      id_str: "759251",
      name: "CNN",
      screen_name: "CNN",
      location: "",
      description:
        "It’s our job to #GoThere & tell the most difficult stories. Join us! For more breaking news updates follow @CNNBRK & download our app https://t.co/UCHG9M367J",
      url: "http://t.co/IaghNW8Xm2",
      entities: [Object],
      protected: false,
      followers_count: 52074757,
      friends_count: 1101,
      listed_count: 145624,
      created_at: "Fri Feb 09 00:35:02 +0000 2007",
      favourites_count: 1418,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 330036,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: true,
      profile_background_color: "323232",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1278259160644227073/MfCyF7CG_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1278259160644227073/MfCyF7CG_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/759251/1607983278",
      profile_link_color: "004287",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "EEEEEE",
      profile_text_color: "000000",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "regular",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 45,
    favorite_count: 143,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
  {
    created_at: "Wed Jan 13 09:21:25 +0000 2021",
    id: 1349285412548849700,
    id_str: "1349285412548849664",
    text:
      "RT @cnni: BREAKING: Russian opposition politician Alexey Navalny says he will return to Russia from Germany, where he has been recovering a…",
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
    source:
      '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 759251,
      id_str: "759251",
      name: "CNN",
      screen_name: "CNN",
      location: "",
      description:
        "It’s our job to #GoThere & tell the most difficult stories. Join us! For more breaking news updates follow @CNNBRK & download our app https://t.co/UCHG9M367J",
      url: "http://t.co/IaghNW8Xm2",
      entities: [Object],
      protected: false,
      followers_count: 52074757,
      friends_count: 1101,
      listed_count: 145624,
      created_at: "Fri Feb 09 00:35:02 +0000 2007",
      favourites_count: 1418,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 330036,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: true,
      profile_background_color: "323232",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1278259160644227073/MfCyF7CG_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1278259160644227073/MfCyF7CG_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/759251/1607983278",
      profile_link_color: "004287",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "EEEEEE",
      profile_text_color: "000000",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "regular",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status: {
      created_at: "Wed Jan 13 09:21:18 +0000 2021",
      id: 1349285385025818600,
      id_str: "1349285385025818624",
      text:
        "BREAKING: Russian opposition politician Alexey Navalny says he will return to Russia from Germany, where he has bee… https://t.co/ebhtSmHHXi",
      truncated: true,
      entities: [Object],
      source:
        '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: [Object],
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 37,
      favorite_count: 92,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: "en",
    },
    is_quote_status: false,
    retweet_count: 37,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: "en",
  },
  {
    created_at: "Wed Jan 13 09:16:05 +0000 2021",
    id: 1349284072309354500,
    id_str: "1349284072309354498",
    text:
      "A firefighter was arrested for unlawful entry of a restricted building and disorderly conduct on Capitol grounds, a… https://t.co/y7ygxkYJv0",
    truncated: true,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
    source: '<a href="http://www.socialflow.com" rel="nofollow">SocialFlow</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 759251,
      id_str: "759251",
      name: "CNN",
      screen_name: "CNN",
      location: "",
      description:
        "It’s our job to #GoThere & tell the most difficult stories. Join us! For more breaking news updates follow @CNNBRK & download our app https://t.co/UCHG9M367J",
      url: "http://t.co/IaghNW8Xm2",
      entities: [Object],
      protected: false,
      followers_count: 52074757,
      friends_count: 1101,
      listed_count: 145624,
      created_at: "Fri Feb 09 00:35:02 +0000 2007",
      favourites_count: 1418,
      utc_offset: null,
      time_zone: null,
      geo_enabled: true,
      verified: true,
      statuses_count: 330036,
      lang: null,
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: true,
      profile_background_color: "323232",
      profile_background_image_url:
        "http://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_image_url_https:
        "https://abs.twimg.com/images/themes/theme1/bg.png",
      profile_background_tile: false,
      profile_image_url:
        "http://pbs.twimg.com/profile_images/1278259160644227073/MfCyF7CG_normal.jpg",
      profile_image_url_https:
        "https://pbs.twimg.com/profile_images/1278259160644227073/MfCyF7CG_normal.jpg",
      profile_banner_url:
        "https://pbs.twimg.com/profile_banners/759251/1607983278",
      profile_link_color: "004287",
      profile_sidebar_border_color: "000000",
      profile_sidebar_fill_color: "EEEEEE",
      profile_text_color: "000000",
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: "regular",
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 165,
    favorite_count: 588,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: "en",
  },
];
